Fix failures in Gold Csv caused by platform-dependent printf rounding
printf has inconsistent rounding behavior accross different platforms, see:
https://www.exploringbinary.com/inconsistent-rounding-of-printed-floating-point-numbers/

This PR adds some comparison code to tolerate rounding errors on the smallest decimal point.

Previously, tests cases 0 and 3 returns respectively:

GoldEtlCsvTests.cpp(110): error: Difference on line: 326
    COLUMN                    TEST VALUE                            GOLD VALUE
    MsUntilDisplayed          16.312                                16.313

GoldEtlCsvTests.cpp(110): error: Difference on line: 119
    COLUMN                    TEST VALUE                            GOLD VALUE
    MsInPresentAPI            0.062                                 0.063

Now both tests pass. Validated via printing that this path is only stepped into in these two cases.

Signed-off-by: Zuoming Shi <ZuomingShi@gmail.com>